name: Docker Build Master arm64
on:
  push:
    paths-ignore:
      - 'README.md' 
      - '.github\workflows\dockerbuild-dev.yml'
      - '.github\workflows\dockerbuild-exp.yml'
      - '.github\workflows\dockerbuild-master.yml'   
      - '.github\workflows\dockerbuildbuild-dev-arm64.yml'
      - '.github\workflows\dockerbuildbuild-master-arm64.yml'
      - '.github\workflows\dockerbuildbuild-dev-armv7.yml'
      - '.github\workflows\dockerbuildbuild-master-armv7.yml'    
    branches: 
      - master
  schedule:
    - cron: '00 0 * * 6'
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PWD: ${{ secrets.DOCKER_PWD }}
      run: |
         docker login -u $DOCKER_USER -p $DOCKER_PWD
    - uses: rlespinasse/github-slug-action@master
    - name: Print slug variables
      run: |
        echo ${{ env.GITHUB_REF_SLUG }}
        echo ${{ env.GITHUB_SHA_SHORT }}
    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1.0.5
      with:
        version: latest
    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}
    - name: Run Buildx
      run: |
        docker buildx build \
        --platform linux/arm64 \
        --tag eafxx/traktarr:arm64 \
        --tag eafxx/traktarr:arm64-${{ env.GITHUB_SHA_SHORT }} \
        --push . \
        --file ./Dockerfile
