name: Docker Build Dev
on:
  push:
    paths-ignore:
      - 'README.md' 
      - '.github\workflows\dockerbuild-dev.yml'
      - '.github\workflows\dockerbuild-exp.yml'
      - '.github\workflows\dockerbuild-master.yml'
    branches: 
      - dev
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PWD: ${{ secrets.DOCKER_PWD }}
      run: |
         docker login -u $DOCKER_USER -p $DOCKER_PWD
    - uses: rlespinasse/github-slug-action@master
    - name: Print slug variables
      run: |
        echo ${{ env.GITHUB_REF_SLUG }}
        echo ${{ env.GITHUB_SHA_SHORT }}
    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1.0.5
      with:
        version: latest
    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}
    - name: Run Buildx amd64
      run: |
        docker buildx build \
        --platform linux/amd64 \
        --tag eafxx/traktarr:dev \
        --push . \
        --file ./Dockerfile
    - name: Run Buildx arm64
      run: |
        docker buildx build \
        --platform linux/arm64 \
        --tag eafxx/traktarr:arm64-dev \
        --push . \
        --file ./Dockerfile.arm64
    - name: Run Buildx armv7
      run: |
        docker buildx build \
        --platform linux/arm/v7 \
        --tag eafxx/traktarr:armv7-dev \
        --push . \
        --file ./Dockerfile.armhf           
